// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.univman.finishedstudent;

import com.univman.finishedstudent.FinishedStudent;
import com.univman.finishedstudent.FinishedStudentDataOnDemand;
import com.univman.finishedstudent.FinishedStudentIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FinishedStudentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FinishedStudentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FinishedStudentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FinishedStudentIntegrationTest: @Transactional;
    
    @Autowired
    FinishedStudentDataOnDemand FinishedStudentIntegrationTest.dod;
    
    @Test
    public void FinishedStudentIntegrationTest.testCountFinishedStudents() {
        Assert.assertNotNull("Data on demand for 'FinishedStudent' failed to initialize correctly", dod.getRandomFinishedStudent());
        long count = FinishedStudent.countFinishedStudents();
        Assert.assertTrue("Counter for 'FinishedStudent' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FinishedStudentIntegrationTest.testFindFinishedStudent() {
        FinishedStudent obj = dod.getRandomFinishedStudent();
        Assert.assertNotNull("Data on demand for 'FinishedStudent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinishedStudent' failed to provide an identifier", id);
        obj = FinishedStudent.findFinishedStudent(id);
        Assert.assertNotNull("Find method for 'FinishedStudent' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FinishedStudent' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FinishedStudentIntegrationTest.testFindAllFinishedStudents() {
        Assert.assertNotNull("Data on demand for 'FinishedStudent' failed to initialize correctly", dod.getRandomFinishedStudent());
        long count = FinishedStudent.countFinishedStudents();
        Assert.assertTrue("Too expensive to perform a find all test for 'FinishedStudent', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FinishedStudent> result = FinishedStudent.findAllFinishedStudents();
        Assert.assertNotNull("Find all method for 'FinishedStudent' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FinishedStudent' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FinishedStudentIntegrationTest.testFindFinishedStudentEntries() {
        Assert.assertNotNull("Data on demand for 'FinishedStudent' failed to initialize correctly", dod.getRandomFinishedStudent());
        long count = FinishedStudent.countFinishedStudents();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FinishedStudent> result = FinishedStudent.findFinishedStudentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FinishedStudent' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FinishedStudent' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FinishedStudentIntegrationTest.testFlush() {
        FinishedStudent obj = dod.getRandomFinishedStudent();
        Assert.assertNotNull("Data on demand for 'FinishedStudent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinishedStudent' failed to provide an identifier", id);
        obj = FinishedStudent.findFinishedStudent(id);
        Assert.assertNotNull("Find method for 'FinishedStudent' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFinishedStudent(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'FinishedStudent' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FinishedStudentIntegrationTest.testMergeUpdate() {
        FinishedStudent obj = dod.getRandomFinishedStudent();
        Assert.assertNotNull("Data on demand for 'FinishedStudent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinishedStudent' failed to provide an identifier", id);
        obj = FinishedStudent.findFinishedStudent(id);
        boolean modified =  dod.modifyFinishedStudent(obj);
        Integer currentVersion = obj.getVersion();
        FinishedStudent merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FinishedStudent' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FinishedStudentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'FinishedStudent' failed to initialize correctly", dod.getRandomFinishedStudent());
        FinishedStudent obj = dod.getNewTransientFinishedStudent(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FinishedStudent' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FinishedStudent' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'FinishedStudent' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FinishedStudentIntegrationTest.testRemove() {
        FinishedStudent obj = dod.getRandomFinishedStudent();
        Assert.assertNotNull("Data on demand for 'FinishedStudent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FinishedStudent' failed to provide an identifier", id);
        obj = FinishedStudent.findFinishedStudent(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'FinishedStudent' with identifier '" + id + "'", FinishedStudent.findFinishedStudent(id));
    }
    
}
