// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.univman.finishedstudent;

import com.univman.finishedstudent.FinishedStudentIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FinishedStudentIntegrationTest_Roo_Configurable {
    
    declare @type: FinishedStudentIntegrationTest: @Configurable;
    
}
