// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.univman.finishedstudent;

import com.univman.finishedstudent.FinishedStudent;
import com.univman.finishedstudent.FinishedStudentDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect FinishedStudentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FinishedStudentDataOnDemand: @Component;
    
    private Random FinishedStudentDataOnDemand.rnd = new SecureRandom();
    
    private List<FinishedStudent> FinishedStudentDataOnDemand.data;
    
    public FinishedStudent FinishedStudentDataOnDemand.getNewTransientFinishedStudent(int index) {
        FinishedStudent obj = new FinishedStudent();
        setFinished(obj, index);
        setMail(obj, index);
        setName(obj, index);
        setPassword(obj, index);
        return obj;
    }
    
    public void FinishedStudentDataOnDemand.setFinished(FinishedStudent obj, int index) {
        Boolean finished = Boolean.TRUE;
        obj.setFinished(finished);
    }
    
    public void FinishedStudentDataOnDemand.setMail(FinishedStudent obj, int index) {
        String mail = "mail_" + index;
        obj.setMail(mail);
    }
    
    public void FinishedStudentDataOnDemand.setName(FinishedStudent obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void FinishedStudentDataOnDemand.setPassword(FinishedStudent obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public FinishedStudent FinishedStudentDataOnDemand.getSpecificFinishedStudent(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        FinishedStudent obj = data.get(index);
        Long id = obj.getId();
        return FinishedStudent.findFinishedStudent(id);
    }
    
    public FinishedStudent FinishedStudentDataOnDemand.getRandomFinishedStudent() {
        init();
        FinishedStudent obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return FinishedStudent.findFinishedStudent(id);
    }
    
    public boolean FinishedStudentDataOnDemand.modifyFinishedStudent(FinishedStudent obj) {
        return false;
    }
    
    public void FinishedStudentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = FinishedStudent.findFinishedStudentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'FinishedStudent' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<FinishedStudent>();
        for (int i = 0; i < 10; i++) {
            FinishedStudent obj = getNewTransientFinishedStudent(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
